---
apiVersion: v1
kind: Secret
metadata:
  name: ticketing-secret
  namespace: ktarasrha-dev
type: Opaque
data:
  POSTGRES_USER:     dGlja2V0aW5nX3VzZXI=
  POSTGRES_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
  POSTGRES_DB:       dGlja2V0aW5n

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing-config
  namespace: ktarasrha-dev
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  REDIS_HOST:    redis
  REDIS_PORT:    "6379"
  API_PORT:      "3000"
  FRONTEND_PORT: "8080"
  QUEUE_NAME:    ticket_orders
  NODE_ENV:      production