---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ticketing-sa
  namespace: ktarasrha-dev
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ticketing-configmap-reader
  namespace: ktarasrha-dev
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ticketing-sa-binding
  namespace: ktarasrha-dev
subjects:
  - kind: ServiceAccount
    name: ticketing-sa
    namespace: ktarasrha-dev
roleRef:
  kind: Role
  name: ticketing-configmap-reader
  apiGroup: rbac.authorization.k8s.io